/*
 * UAVCAN data structure definition for libuavcan.
 *
 * Autogenerated, do not edit.
 *
 * Source file: /home/joao/PESTA/control_system/v3/dsdl_source/Airspeed.uavcan
 */

#ifndef DSDL_SOURCE_AIRSPEED_HPP_INCLUDED
#define DSDL_SOURCE_AIRSPEED_HPP_INCLUDED

#include <uavcan/build_config.hpp>
#include <uavcan/node/global_data_type_registry.hpp>
#include <uavcan/marshal/types.hpp>

/******************************* Source text **********************************
#
# Generic status message to report Airspeed data
#

#
# Airspeed in m/s
#
float16 airspeed
#
# Temperature in degC
#
float16 temperature

bool health
******************************************************************************/

/********************* DSDL signature source definition ***********************
dsdl_source.Airspeed
saturated float16 airspeed
saturated float16 temperature
saturated bool health
******************************************************************************/

#undef airspeed
#undef temperature
#undef health

namespace dsdl_source
{

template <int _tmpl>
struct UAVCAN_EXPORT Airspeed_
{
    typedef const Airspeed_<_tmpl>& ParameterType;
    typedef Airspeed_<_tmpl>& ReferenceType;

    struct ConstantTypes
    {
    };

    struct FieldTypes
    {
        typedef ::uavcan::FloatSpec< 16, ::uavcan::CastModeSaturate > airspeed;
        typedef ::uavcan::FloatSpec< 16, ::uavcan::CastModeSaturate > temperature;
        typedef ::uavcan::IntegerSpec< 1, ::uavcan::SignednessUnsigned, ::uavcan::CastModeSaturate > health;
    };

    enum
    {
        MinBitLen
            = FieldTypes::airspeed::MinBitLen
            + FieldTypes::temperature::MinBitLen
            + FieldTypes::health::MinBitLen
    };

    enum
    {
        MaxBitLen
            = FieldTypes::airspeed::MaxBitLen
            + FieldTypes::temperature::MaxBitLen
            + FieldTypes::health::MaxBitLen
    };

    // Constants

    // Fields
    typename ::uavcan::StorageType< typename FieldTypes::airspeed >::Type airspeed;
    typename ::uavcan::StorageType< typename FieldTypes::temperature >::Type temperature;
    typename ::uavcan::StorageType< typename FieldTypes::health >::Type health;

    Airspeed_()
        : airspeed()
        , temperature()
        , health()
    {
        ::uavcan::StaticAssert<_tmpl == 0>::check();  // Usage check

#if UAVCAN_DEBUG
        /*
         * Cross-checking MaxBitLen provided by the DSDL compiler.
         * This check shall never be performed in user code because MaxBitLen value
         * actually depends on the nested types, thus it is not invariant.
         */
        ::uavcan::StaticAssert<33 == MaxBitLen>::check();
#endif
    }

    bool operator==(ParameterType rhs) const;
    bool operator!=(ParameterType rhs) const { return !operator==(rhs); }

    /**
     * This comparison is based on @ref uavcan::areClose(), which ensures proper comparison of
     * floating point fields at any depth.
     */
    bool isClose(ParameterType rhs) const;

    static int encode(ParameterType self, ::uavcan::ScalarCodec& codec,
                      ::uavcan::TailArrayOptimizationMode tao_mode = ::uavcan::TailArrayOptEnabled);

    static int decode(ReferenceType self, ::uavcan::ScalarCodec& codec,
                      ::uavcan::TailArrayOptimizationMode tao_mode = ::uavcan::TailArrayOptEnabled);

    /*
     * Static type info
     */
    enum { DataTypeKind = ::uavcan::DataTypeKindMessage };
    // This type has no default data type ID

    static const char* getDataTypeFullName()
    {
        return "dsdl_source.Airspeed";
    }

    static void extendDataTypeSignature(::uavcan::DataTypeSignature& signature)
    {
        signature.extend(getDataTypeSignature());
    }

    static ::uavcan::DataTypeSignature getDataTypeSignature();

};

/*
 * Out of line struct method definitions
 */

template <int _tmpl>
bool Airspeed_<_tmpl>::operator==(ParameterType rhs) const
{
    return
        airspeed == rhs.airspeed &&
        temperature == rhs.temperature &&
        health == rhs.health;
}

template <int _tmpl>
bool Airspeed_<_tmpl>::isClose(ParameterType rhs) const
{
    return
        ::uavcan::areClose(airspeed, rhs.airspeed) &&
        ::uavcan::areClose(temperature, rhs.temperature) &&
        ::uavcan::areClose(health, rhs.health);
}

template <int _tmpl>
int Airspeed_<_tmpl>::encode(ParameterType self, ::uavcan::ScalarCodec& codec,
    ::uavcan::TailArrayOptimizationMode tao_mode)
{
    (void)self;
    (void)codec;
    (void)tao_mode;
    int res = 1;
    res = FieldTypes::airspeed::encode(self.airspeed, codec,  ::uavcan::TailArrayOptDisabled);
    if (res <= 0)
    {
        return res;
    }
    res = FieldTypes::temperature::encode(self.temperature, codec,  ::uavcan::TailArrayOptDisabled);
    if (res <= 0)
    {
        return res;
    }
    res = FieldTypes::health::encode(self.health, codec,  tao_mode);
    return res;
}

template <int _tmpl>
int Airspeed_<_tmpl>::decode(ReferenceType self, ::uavcan::ScalarCodec& codec,
    ::uavcan::TailArrayOptimizationMode tao_mode)
{
    (void)self;
    (void)codec;
    (void)tao_mode;
    int res = 1;
    res = FieldTypes::airspeed::decode(self.airspeed, codec,  ::uavcan::TailArrayOptDisabled);
    if (res <= 0)
    {
        return res;
    }
    res = FieldTypes::temperature::decode(self.temperature, codec,  ::uavcan::TailArrayOptDisabled);
    if (res <= 0)
    {
        return res;
    }
    res = FieldTypes::health::decode(self.health, codec,  tao_mode);
    return res;
}

/*
 * Out of line type method definitions
 */
template <int _tmpl>
::uavcan::DataTypeSignature Airspeed_<_tmpl>::getDataTypeSignature()
{
    ::uavcan::DataTypeSignature signature(0xF58153877B786A9EULL);

    FieldTypes::airspeed::extendDataTypeSignature(signature);
    FieldTypes::temperature::extendDataTypeSignature(signature);
    FieldTypes::health::extendDataTypeSignature(signature);

    return signature;
}

/*
 * Out of line constant definitions
 */

/*
 * Final typedef
 */
typedef Airspeed_<0> Airspeed;

// No default registration

} // Namespace dsdl_source

/*
 * YAML streamer specialization
 */
namespace uavcan
{

template <>
class UAVCAN_EXPORT YamlStreamer< ::dsdl_source::Airspeed >
{
public:
    template <typename Stream>
    static void stream(Stream& s, ::dsdl_source::Airspeed::ParameterType obj, const int level);
};

template <typename Stream>
void YamlStreamer< ::dsdl_source::Airspeed >::stream(Stream& s, ::dsdl_source::Airspeed::ParameterType obj, const int level)
{
    (void)s;
    (void)obj;
    (void)level;
    if (level > 0)
    {
        s << '\n';
        for (int pos = 0; pos < level; pos++)
        {
            s << "  ";
        }
    }
    s << "airspeed: ";
    YamlStreamer< ::dsdl_source::Airspeed::FieldTypes::airspeed >::stream(s, obj.airspeed, level + 1);
    s << '\n';
    for (int pos = 0; pos < level; pos++)
    {
        s << "  ";
    }
    s << "temperature: ";
    YamlStreamer< ::dsdl_source::Airspeed::FieldTypes::temperature >::stream(s, obj.temperature, level + 1);
    s << '\n';
    for (int pos = 0; pos < level; pos++)
    {
        s << "  ";
    }
    s << "health: ";
    YamlStreamer< ::dsdl_source::Airspeed::FieldTypes::health >::stream(s, obj.health, level + 1);
}

}

namespace dsdl_source
{

template <typename Stream>
inline Stream& operator<<(Stream& s, ::dsdl_source::Airspeed::ParameterType obj)
{
    ::uavcan::YamlStreamer< ::dsdl_source::Airspeed >::stream(s, obj, 0);
    return s;
}

} // Namespace dsdl_source

#endif // DSDL_SOURCE_AIRSPEED_HPP_INCLUDED