/*
 * UAVCAN data structure definition for libuavcan.
 *
 * Autogenerated, do not edit.
 *
 * Source file: /home/joao/PESTA/control_system/v3/dsdl_source/Magnetometer.uavcan
 */

#ifndef DSDL_SOURCE_MAGNETOMETER_HPP_INCLUDED
#define DSDL_SOURCE_MAGNETOMETER_HPP_INCLUDED

#include <uavcan/build_config.hpp>
#include <uavcan/node/global_data_type_registry.hpp>
#include <uavcan/marshal/types.hpp>

/******************************* Source text **********************************
#
# Magnetic field readings, in Gauss, in body frame.
#
float16[3] magnetic_field_ga

bool health
******************************************************************************/

/********************* DSDL signature source definition ***********************
dsdl_source.Magnetometer
saturated float16[3] magnetic_field_ga
saturated bool health
******************************************************************************/

#undef magnetic_field_ga
#undef health

namespace dsdl_source
{

template <int _tmpl>
struct UAVCAN_EXPORT Magnetometer_
{
    typedef const Magnetometer_<_tmpl>& ParameterType;
    typedef Magnetometer_<_tmpl>& ReferenceType;

    struct ConstantTypes
    {
    };

    struct FieldTypes
    {
        typedef ::uavcan::Array< ::uavcan::FloatSpec< 16, ::uavcan::CastModeSaturate >, ::uavcan::ArrayModeStatic, 3 > magnetic_field_ga;
        typedef ::uavcan::IntegerSpec< 1, ::uavcan::SignednessUnsigned, ::uavcan::CastModeSaturate > health;
    };

    enum
    {
        MinBitLen
            = FieldTypes::magnetic_field_ga::MinBitLen
            + FieldTypes::health::MinBitLen
    };

    enum
    {
        MaxBitLen
            = FieldTypes::magnetic_field_ga::MaxBitLen
            + FieldTypes::health::MaxBitLen
    };

    // Constants

    // Fields
    typename ::uavcan::StorageType< typename FieldTypes::magnetic_field_ga >::Type magnetic_field_ga;
    typename ::uavcan::StorageType< typename FieldTypes::health >::Type health;

    Magnetometer_()
        : magnetic_field_ga()
        , health()
    {
        ::uavcan::StaticAssert<_tmpl == 0>::check();  // Usage check

#if UAVCAN_DEBUG
        /*
         * Cross-checking MaxBitLen provided by the DSDL compiler.
         * This check shall never be performed in user code because MaxBitLen value
         * actually depends on the nested types, thus it is not invariant.
         */
        ::uavcan::StaticAssert<49 == MaxBitLen>::check();
#endif
    }

    bool operator==(ParameterType rhs) const;
    bool operator!=(ParameterType rhs) const { return !operator==(rhs); }

    /**
     * This comparison is based on @ref uavcan::areClose(), which ensures proper comparison of
     * floating point fields at any depth.
     */
    bool isClose(ParameterType rhs) const;

    static int encode(ParameterType self, ::uavcan::ScalarCodec& codec,
                      ::uavcan::TailArrayOptimizationMode tao_mode = ::uavcan::TailArrayOptEnabled);

    static int decode(ReferenceType self, ::uavcan::ScalarCodec& codec,
                      ::uavcan::TailArrayOptimizationMode tao_mode = ::uavcan::TailArrayOptEnabled);

    /*
     * Static type info
     */
    enum { DataTypeKind = ::uavcan::DataTypeKindMessage };
    // This type has no default data type ID

    static const char* getDataTypeFullName()
    {
        return "dsdl_source.Magnetometer";
    }

    static void extendDataTypeSignature(::uavcan::DataTypeSignature& signature)
    {
        signature.extend(getDataTypeSignature());
    }

    static ::uavcan::DataTypeSignature getDataTypeSignature();

};

/*
 * Out of line struct method definitions
 */

template <int _tmpl>
bool Magnetometer_<_tmpl>::operator==(ParameterType rhs) const
{
    return
        magnetic_field_ga == rhs.magnetic_field_ga &&
        health == rhs.health;
}

template <int _tmpl>
bool Magnetometer_<_tmpl>::isClose(ParameterType rhs) const
{
    return
        ::uavcan::areClose(magnetic_field_ga, rhs.magnetic_field_ga) &&
        ::uavcan::areClose(health, rhs.health);
}

template <int _tmpl>
int Magnetometer_<_tmpl>::encode(ParameterType self, ::uavcan::ScalarCodec& codec,
    ::uavcan::TailArrayOptimizationMode tao_mode)
{
    (void)self;
    (void)codec;
    (void)tao_mode;
    int res = 1;
    res = FieldTypes::magnetic_field_ga::encode(self.magnetic_field_ga, codec,  ::uavcan::TailArrayOptDisabled);
    if (res <= 0)
    {
        return res;
    }
    res = FieldTypes::health::encode(self.health, codec,  tao_mode);
    return res;
}

template <int _tmpl>
int Magnetometer_<_tmpl>::decode(ReferenceType self, ::uavcan::ScalarCodec& codec,
    ::uavcan::TailArrayOptimizationMode tao_mode)
{
    (void)self;
    (void)codec;
    (void)tao_mode;
    int res = 1;
    res = FieldTypes::magnetic_field_ga::decode(self.magnetic_field_ga, codec,  ::uavcan::TailArrayOptDisabled);
    if (res <= 0)
    {
        return res;
    }
    res = FieldTypes::health::decode(self.health, codec,  tao_mode);
    return res;
}

/*
 * Out of line type method definitions
 */
template <int _tmpl>
::uavcan::DataTypeSignature Magnetometer_<_tmpl>::getDataTypeSignature()
{
    ::uavcan::DataTypeSignature signature(0xA45031B2F66D3A2CULL);

    FieldTypes::magnetic_field_ga::extendDataTypeSignature(signature);
    FieldTypes::health::extendDataTypeSignature(signature);

    return signature;
}

/*
 * Out of line constant definitions
 */

/*
 * Final typedef
 */
typedef Magnetometer_<0> Magnetometer;

// No default registration

} // Namespace dsdl_source

/*
 * YAML streamer specialization
 */
namespace uavcan
{

template <>
class UAVCAN_EXPORT YamlStreamer< ::dsdl_source::Magnetometer >
{
public:
    template <typename Stream>
    static void stream(Stream& s, ::dsdl_source::Magnetometer::ParameterType obj, const int level);
};

template <typename Stream>
void YamlStreamer< ::dsdl_source::Magnetometer >::stream(Stream& s, ::dsdl_source::Magnetometer::ParameterType obj, const int level)
{
    (void)s;
    (void)obj;
    (void)level;
    if (level > 0)
    {
        s << '\n';
        for (int pos = 0; pos < level; pos++)
        {
            s << "  ";
        }
    }
    s << "magnetic_field_ga: ";
    YamlStreamer< ::dsdl_source::Magnetometer::FieldTypes::magnetic_field_ga >::stream(s, obj.magnetic_field_ga, level + 1);
    s << '\n';
    for (int pos = 0; pos < level; pos++)
    {
        s << "  ";
    }
    s << "health: ";
    YamlStreamer< ::dsdl_source::Magnetometer::FieldTypes::health >::stream(s, obj.health, level + 1);
}

}

namespace dsdl_source
{

template <typename Stream>
inline Stream& operator<<(Stream& s, ::dsdl_source::Magnetometer::ParameterType obj)
{
    ::uavcan::YamlStreamer< ::dsdl_source::Magnetometer >::stream(s, obj, 0);
    return s;
}

} // Namespace dsdl_source

#endif // DSDL_SOURCE_MAGNETOMETER_HPP_INCLUDED